# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.7"
  - "3.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install tensorflow
  - pip install coverage

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source pincelate setup.py test --verbose

after_success:
- pip install coveralls
- coveralls # send coverage to coveralls.io

after_script:
- coverage report                     # show coverage on cmd line
- pip install pycodestyle pyflakes
- pyflakes . | tee >(wc -l)           # static analysis
- pycodestyle --statistics --count .  # static analysis
